apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: keycloak
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak01  
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 9080
    targetPort: 8080      
  selector:
    app: keycloak
  type: LoadBalancer  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:19.0.1
        args: ["start-dev --import-realm"]
        volumeMounts:
        - mountPath: "/opt/keycloak/data/import/keycloak-realm.json"
          name: "opt-keycloak-data-import"
          readOnly: true
          subPathExpr: "keycloak-realm.json"
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_ADDR
          value: keycloak-db-postgresql-ha-pgpool
        - name: DB_DATABASE
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-db-postgresql-ha-postgresql
              key: postgresql-password
        - name: DB_SCHEMA
          value: public
        - name: DB_VENDOR
          value: POSTGRES
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: dns.DNS_PING
        - name: JGROUPS_DISCOVERY_PROPERTIES
          value: "dns_query=keycloak"
        - name: CACHE_OWNERS_COUNT
          value: "2"
        - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
          value: "2"
        - name: KC_HOSTNAME
          value: h1.localtest.me
        # - name: KC_HTTP_RELATIVE_PATH
        #   value: "/auth"
        ports:
          - name: jgroups
            containerPort: 7600
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
      volumes:      
      - name: opt-keycloak-data-import
        configMap:
          name: keycloak-realm-configmap          
